### ISSUE TITLE
"not possible to parse your key" error in Laravel

### ISSUE THREAD

**Issue by francishcchoi** [creativetimofficial/ct-vue-black-dashboard-pro-laravel#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

No such error

# Current Behavior

When login, the server failed with the error "not possible to parse your key" in Laravel log.  As a result, cannot login.  The detail log is as follows:

# Failure Information (for bugs)

[2021-11-25 13:54:10] local.ERROR: It was not possible to parse your key, reason:  {"exception":"[object] (Lcobucci\\JWT\\Signer\\InvalidKeyProvided(code: 0): It was not possible to parse your key, reason:  at C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\lcobucci\\jwt\\src\\Signer\\InvalidKeyProvided.php:17)
[stacktrace]
#0 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\lcobucci\\jwt\\src\\Signer\\OpenSSL.php(85): Lcobucci\\JWT\\Signer\\InvalidKeyProvided::cannotBeParsed(false)
#1 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\lcobucci\\jwt\\src\\Signer\\OpenSSL.php(42): Lcobucci\\JWT\\Signer\\OpenSSL->validateKey(Object(OpenSSLAsymmetricKey))
#2 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\lcobucci\\jwt\\src\\Signer\\OpenSSL.php(18): Lcobucci\\JWT\\Signer\\OpenSSL->getPrivateKey('file://C:\\\\WorkW...', '')
#3 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\lcobucci\\jwt\\src\\Signer\\BaseSigner.php(38): Lcobucci\\JWT\\Signer\\OpenSSL->createHash('eyJ0eXAiOiJKV1Q...', Object(Lcobucci\\JWT\\Signer\\Key\\LocalFileReference))
#4 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\lcobucci\\jwt\\src\\Builder.php(568): Lcobucci\\JWT\\Signer\\BaseSigner->sign('eyJ0eXAiOiJKV1Q...', Object(Lcobucci\\JWT\\Signer\\Key\\LocalFileReference))
#5 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\lcobucci\\jwt\\src\\Builder.php(529): Lcobucci\\JWT\\Builder->createSignature('eyJ0eXAiOiJKV1Q...', Object(Lcobucci\\JWT\\Signer\\Rsa\\Sha256), Object(Lcobucci\\JWT\\Signer\\Key\\LocalFileReference))
#6 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\league\\oauth2-server\\src\\Entities\\Traits\\AccessTokenTrait.php(71): Lcobucci\\JWT\\Builder->getToken(Object(Lcobucci\\JWT\\Signer\\Rsa\\Sha256), Object(Lcobucci\\JWT\\Signer\\Key\\LocalFileReference))
#7 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\league\\oauth2-server\\src\\Entities\\Traits\\AccessTokenTrait.php(79): Laravel\\Passport\\Bridge\\AccessToken->convertToJWT()
#8 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\league\\oauth2-server\\src\\ResponseTypes\\BearerTokenResponse.php(31): Laravel\\Passport\\Bridge\\AccessToken->__toString()
#9 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\league\\oauth2-server\\src\\AuthorizationServer.php(202): League\\OAuth2\\Server\\ResponseTypes\\BearerTokenResponse->generateHttpResponse(Object(Nyholm\\Psr7\\Response))
#10 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\passport\\src\\Http\\Controllers\\AccessTokenController.php(65): League\\OAuth2\\Server\\AuthorizationServer->respondToAccessTokenRequest(Object(Nyholm\\Psr7\\ServerRequest), Object(Nyholm\\Psr7\\Response))
#11 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\passport\\src\\Http\\Controllers\\HandlesOAuthErrors.php(24): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->Laravel\\Passport\\Http\\Controllers\\{closure}()
#12 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\passport\\src\\Http\\Controllers\\AccessTokenController.php(67): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->withErrorHandling(Object(Closure))
#13 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(48): Laravel\\Passport\\Http\\Controllers\\AccessTokenController->issueToken(Object(Nyholm\\Psr7\\ServerRequest))
#14 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Passport\\Http\\Controllers\\AccessTokenController), 'issueToken')
#15 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#16 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(693): Illuminate\\Routing\\Route->run()
#17 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(63): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#20 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#24 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#25 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#26 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#27 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#42 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#43 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#44 {main}
"} 

## Steps to Reproduce

1. click the "Get Started" button to login.
2. An "Invalid Credentials" error pops up
3. Check the laravel log and will find the above error

## Context

* Device:  Intel PC
* Operating System:  Win10 Pro
* Browser and Version:  Microsoft Edge Version 96.0.1054.29 (Official build) (64-bit)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @francishcchoi,

Thank you for reporting this issue and for using Creative Tim products. 

Could you check what PHP version are you using? As you can see on https://packagist.org/packages/lcobucci/jwt#3.3.3,  JWT package is officially not compatible with PHP 8. You should upgrade it to a compatible version (at least v4), or downgrade your PHP version to v7.

Please let us know if this worked.

Best,
UPDIVISION Team

**Comment by francishcchoi** [comment]
It works after falling back to php 7.  Thx.

**Comment by teamupdivision** [comment]
Hi there @francishcchoi, 

Thank you very much for the update and for letting us know. 
Please let us know if you will have any other issues. 

All the best,
Updivision Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
