### ISSUE TITLE
Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by francishcchoi** [creativetimofficial/ct-vue-black-dashboard-pro-laravel#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Y ] I am running the latest version
- [ Y] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Should be able to login without any error

# Current Behavior

Fail to login.

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click "Get Started" button the login screen
2. An error "Invalid Credentials" popped up
3. Check the laravel log and it shows "Trying to get property 'id' of non-object" error

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Intel PC
* Operating System: Win10 Pro
* Browser and Version:  Edge Version 96.0.1054.34 (Official build) (64-bit)
* PHP 7.4.26
* Apache 2.4
* MariaDB 10.4.22

In the DB, there are records in the table "users" but no records in the table "oauth_clients".

## Failure Logs

[2021-11-27 06:34:09] local.ERROR: Trying to get property 'id' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object at C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\app\\Http\\Controllers\\Api\\V1\\Auth\\LoginController.php:32)
[stacktrace]
#0 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\app\\Http\\Controllers\\Api\\V1\\Auth\\LoginController.php(32): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', 'C:\\\\WorkWonders\\\\...', 32, Array)
#1 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\Api\\V1\\Auth\\LoginController->__invoke(Object(App\\Http\\Requests\\Api\\V1\\Auth\\LoginRequest))
#2 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
#3 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\V1\\Auth\\LoginController), '__invoke')
#4 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
#5 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(693): Illuminate\\Routing\\Route->run()
#6 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\app\\Http\\Middleware\\JsonApi.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): App\\Http\\Middleware\\JsonApi->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(63): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest(Object(Illuminate\\Http\\Request), Object(Closure), Array)
#13 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), '60', '1')
#14 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#17 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#18 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#19 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#20 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#36 C:\\WorkWonders\\vue-black-dashboard-pro-laravel\\laravel-json-api-pro\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#37 {main}
"}

**Comment by francishcchoi** [comment]
Resolved after reinstall passport

**Comment by teamupdivision** [comment]
Hi @francishcchoi,

Thanks for reporting this and for using Creative Tim products. In case you have any other issues, please contact us. 

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
