### ISSUE TITLE
auth.js:9 Uncaught TypeError: ue.VueAuthenticate is not a constructor

### ISSUE THREAD

**Issue by nicklinn** [creativetimofficial/ct-vue-black-dashboard-pro-laravel#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Login form displayed

# Current Behavior

Blank page with js error: see:  https://affiliates.affiliatedao.xyz/

# Failure Information (for bugs)

Console error:
auth.js:9 Uncaught TypeError: ue.VueAuthenticate is not a constructor
    at Module.56d7 (auth.js:9:17)
    at l (bootstrap:89:22)
    at Object.0 (app.d2f21fb8.js:1:3482)
    at l (bootstrap:89:22)
    at a (bootstrap:45:15)
    at bootstrap:267:10
    at app.d2f21fb8.js:1:3452

## Steps to Reproduce

Install,
npm run build 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:  PC
* Operating System: Windows
* Browser and Version: Chrome Version 100.0.4896.127 (Official Build) (64-bit)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @nicklinn,

Thank you for using the Creative Tim products.

Regarding your reported issue, we believe you might have a misspelling there. 

Your error is "ue.VueAuthenticate is not a constructor" because you are missing a "v" in the beginning. Please try using "vue.VueAuthenticate" and see if it works.

Should you have any other issues or questions, please let us know.

Best,
UPDIVISION Team

**Comment by nicklinn** [comment]
Hello @teamupdivision 

I have found the issue,

on /src/store/modules/auth.js line 3
import { VueAuthenticate } from "vue-authenticate";
should be 
import VueAuthenticate from "vue-authenticate";

**Comment by teamupdivision** [comment]
Hi @nicklinn,

We are glad the issue is solved now.

Please feel free to contact us if you need any further information.

Best,
UPDIVISION Team
